name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      artifact: build.zip
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install Dependencies"
      run: |
        npm install yarn
        yarn

    - name: "Build project"
      run: yarn export
    
    - name: "Zip project"
      run: |
        zip -r ${{ env.artifact }} out/

    - name: "Upload build artifacts for deploy"
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ${{ env.artifact }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: "Download build artifacts from build"
      uses: actions/download-artifact@v2
      with:
        name: artifacts
    
    - name: "Configure AWS credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp build.zip s3://builds.radar.career.infinityworks
