name: Build

on:
  push:
    branches:
      - 'feature/**'
      - '!master'
      - '!README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: "Install Dependencies"
      run: |
        npm install yarn
        yarn

    - name: "Build project"
      run: yarn export